// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsNational")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Championships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Італія",
                            IsNational = true,
                            Name = "Серія А"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Італія",
                            IsNational = true,
                            Name = "Кубок Італії"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Іспанія",
                            IsNational = true,
                            Name = "Ла-Ліга"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Іспанія",
                            IsNational = true,
                            Name = "Кубок Іспанії"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Англія",
                            IsNational = true,
                            Name = "Прем'єр-ліга"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Англія",
                            IsNational = true,
                            Name = "Кубок Англії"
                        },
                        new
                        {
                            Id = 7,
                            Country = "",
                            IsNational = false,
                            Name = "Ліга чемпіонів УЄФА"
                        });
                });

            modelBuilder.Entity("Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Войчех Шченсний",
                            Number = "1",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Леонардо Бонуччі",
                            Number = "19",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Матейс де Лігт",
                            Number = "4",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Алекс Сандро",
                            Number = "12",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Даніло",
                            Number = "13",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Миралем Пяніч",
                            Number = "5",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Блез Матюіді",
                            Number = "14",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Айрон Ремзі",
                            Number = "8",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Пауло Дібала",
                            Number = "10",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Фредеріко Бернандескі",
                            Number = "33",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Кріштіану Роналду",
                            Number = "7",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Марк-Андре тер Штеген",
                            Number = "22",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Нелсон Семеду",
                            Number = "2",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Жерар Піке",
                            Number = "3",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Жоржи Альба",
                            Number = "18",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Самюель Умтіті",
                            Number = "23",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Артуро Відаль",
                            Number = "22",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Френкі де йонг",
                            Number = "21",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Усман Дембеле",
                            Number = "11",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "Антуан Грізман",
                            Number = "17",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Луіс Суарес",
                            Number = "9",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ліонель Мессі",
                            Number = "10",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Алісон Беккер",
                            Number = "13",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Трент Александр-Арнольд",
                            Number = "66",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Вірджил ван Дейк",
                            Number = "4",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "Джо Гомес",
                            Number = "12",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ендрю Робертсон",
                            Number = "26",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Садіо Мане",
                            Number = "10",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "Джордан Хендерсон",
                            Number = "14",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "Фабіньйо",
                            Number = "3",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "Мохамед салах",
                            Number = "11",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "Роберто Фірміно",
                            Number = "9",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "Дивок Орігі",
                            Number = "27",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Coaches")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("GameScheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Турин",
                            Coaches = "Мауріціо Саррі",
                            Country = "Італія",
                            GameScheme = "2-4-4",
                            Name = "Ювентус"
                        },
                        new
                        {
                            Id = 2,
                            City = "Барселона",
                            Coaches = "Ернесто Вальверде",
                            Country = "Іспанія",
                            GameScheme = "2-4-4",
                            Name = "Барселона"
                        },
                        new
                        {
                            Id = 3,
                            City = "Енфілд",
                            Coaches = "Юрген Клопп",
                            Country = "Англія",
                            GameScheme = "2-4-4",
                            Name = "Ліверпуль"
                        });
                });

            modelBuilder.Entity("Data.TeamStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChampion")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamStatistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1983/84"
                        },
                        new
                        {
                            Id = 2,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1985/86"
                        },
                        new
                        {
                            Id = 3,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1994/95"
                        },
                        new
                        {
                            Id = 4,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1996/97"
                        },
                        new
                        {
                            Id = 5,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1997/98"
                        },
                        new
                        {
                            Id = 6,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2001/02"
                        },
                        new
                        {
                            Id = 7,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2002/03"
                        },
                        new
                        {
                            Id = 8,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2004/05"
                        },
                        new
                        {
                            Id = 9,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2005/06"
                        },
                        new
                        {
                            Id = 10,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2011/12"
                        },
                        new
                        {
                            Id = 11,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2012/13"
                        },
                        new
                        {
                            Id = 12,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2013/14"
                        },
                        new
                        {
                            Id = 13,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2014/15"
                        },
                        new
                        {
                            Id = 14,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2015/16"
                        },
                        new
                        {
                            Id = 15,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2016/17"
                        },
                        new
                        {
                            Id = 16,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2017/18"
                        },
                        new
                        {
                            Id = 17,
                            ChampionshipId = 1,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2018/19"
                        },
                        new
                        {
                            Id = 18,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1982/83"
                        },
                        new
                        {
                            Id = 19,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1989/90"
                        },
                        new
                        {
                            Id = 20,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1994/95"
                        },
                        new
                        {
                            Id = 21,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2014/15"
                        },
                        new
                        {
                            Id = 22,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2015/16"
                        },
                        new
                        {
                            Id = 23,
                            ChampionshipId = 2,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "2017/18"
                        },
                        new
                        {
                            Id = 24,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1984/85"
                        },
                        new
                        {
                            Id = 25,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 1,
                            Years = "1995/96"
                        },
                        new
                        {
                            Id = 26,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1992/93"
                        },
                        new
                        {
                            Id = 27,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1994/95"
                        },
                        new
                        {
                            Id = 28,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1998/99"
                        },
                        new
                        {
                            Id = 29,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2004/05"
                        },
                        new
                        {
                            Id = 30,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2005/06"
                        },
                        new
                        {
                            Id = 31,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2008/09"
                        },
                        new
                        {
                            Id = 32,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2009/10"
                        },
                        new
                        {
                            Id = 33,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2010/11"
                        },
                        new
                        {
                            Id = 34,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2012/13"
                        },
                        new
                        {
                            Id = 35,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2014/15"
                        },
                        new
                        {
                            Id = 36,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2015/16"
                        },
                        new
                        {
                            Id = 37,
                            ChampionshipId = 3,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2017/18"
                        },
                        new
                        {
                            Id = 38,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1978"
                        },
                        new
                        {
                            Id = 39,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1981"
                        },
                        new
                        {
                            Id = 40,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1988"
                        },
                        new
                        {
                            Id = 41,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1990"
                        },
                        new
                        {
                            Id = 42,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1997"
                        },
                        new
                        {
                            Id = 43,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1998"
                        },
                        new
                        {
                            Id = 44,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2009"
                        },
                        new
                        {
                            Id = 45,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2012"
                        },
                        new
                        {
                            Id = 46,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2015"
                        },
                        new
                        {
                            Id = 47,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2016"
                        },
                        new
                        {
                            Id = 48,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2017"
                        },
                        new
                        {
                            Id = 49,
                            ChampionshipId = 4,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2018"
                        },
                        new
                        {
                            Id = 50,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "1992"
                        },
                        new
                        {
                            Id = 51,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2006"
                        },
                        new
                        {
                            Id = 52,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2009"
                        },
                        new
                        {
                            Id = 53,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2011"
                        },
                        new
                        {
                            Id = 54,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 2,
                            Years = "2015"
                        },
                        new
                        {
                            Id = 55,
                            ChampionshipId = 5,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1979/80"
                        },
                        new
                        {
                            Id = 56,
                            ChampionshipId = 5,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1981/82"
                        },
                        new
                        {
                            Id = 57,
                            ChampionshipId = 5,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1985/86"
                        },
                        new
                        {
                            Id = 58,
                            ChampionshipId = 5,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1987/88"
                        },
                        new
                        {
                            Id = 59,
                            ChampionshipId = 5,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1989/90"
                        },
                        new
                        {
                            Id = 60,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1965"
                        },
                        new
                        {
                            Id = 61,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1974"
                        },
                        new
                        {
                            Id = 62,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1986"
                        },
                        new
                        {
                            Id = 63,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1989"
                        },
                        new
                        {
                            Id = 64,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1992"
                        },
                        new
                        {
                            Id = 65,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "2001"
                        },
                        new
                        {
                            Id = 66,
                            ChampionshipId = 6,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "2006"
                        },
                        new
                        {
                            Id = 67,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1977"
                        },
                        new
                        {
                            Id = 68,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1978"
                        },
                        new
                        {
                            Id = 69,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1981"
                        },
                        new
                        {
                            Id = 70,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "1984"
                        },
                        new
                        {
                            Id = 71,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "2005"
                        },
                        new
                        {
                            Id = 72,
                            ChampionshipId = 7,
                            IsChampion = true,
                            TeamId = 3,
                            Years = "2019"
                        });
                });

            modelBuilder.Entity("Data.Player", b =>
                {
                    b.HasOne("Data.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.TeamStatistic", b =>
                {
                    b.HasOne("Data.Championship", "Championship")
                        .WithMany()
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
